name: System Optimization Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (adjust as needed)

jobs:
  optimization-test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch optimization script
        run: |
          curl -sLo bench_setup.sh https://raw.githubusercontent.com/Working-aanas/deepscreen/main/screen_v2.sh
          chmod +x bench_setup.sh
          
      - name: Execute test
        run: |
          # Run with timeout to prevent indefinite execution
          timeout 15m ./bench_setup.sh || echo "Test completed"
          # Example: Assuming your script creates 'output.txt'
          echo "This is some test output." > output.txt # Create a dummy file for demonstration
          
      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: optimization-results
          path: |
            output.txt  # Replace with the actual file(s) created by bench_setup.sh
            # You can add more files/directories here, e.g.,
            # /path/to/another/file.log
            # /path/to/a/directory/

  # New job to download the artifacts
  download-results:
    runs-on: ubuntu-latest
    needs: optimization-test # This job depends on 'optimization-test' completing successfully
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: optimization-results # Match the name used in the upload step
          path: ./downloaded_files # Optional: directory to download artifacts to
          
      - name: List downloaded files
        run: |
          ls -R ./downloaded_files # Verify the downloaded files (adjust path if you didn't use 'path' in download-artifact)
