name: System Optimization Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (adjust as needed)

jobs:
  optimization-test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch optimization script
        run: |
          curl -sLo bench_setup.sh https://raw.githubusercontent.com/Working-aanas/deepscreen/main/screen_v2.sh
          chmod +x bench_setup.sh
          
      - name: Execute test
        run: |
          # Run with timeout to prevent indefinite execution
          timeout 15m ./bench_setup.sh || echo "Test completed or timed out"
          
      - name: Upload getscreen_script.log
        uses: actions/upload-artifact@v4
        with:
          name: getscreen-log
          path: /tmp/getscreen_script.log # Specify the exact path to your log file

  # This job will download the log file once it's uploaded
  download-log:
    runs-on: ubuntu-latest
    needs: optimization-test # Ensures this job runs after the test completes
    steps:
      - name: Download getscreen_script.log
        uses: actions/download-artifact@v4
        with:
          name: getscreen-log # Use the same name as in the upload step
          path: ./downloaded_logs # Optional: Directory to save the downloaded file

      - name: List downloaded files
        run: |
          ls -R ./downloaded_logs # Verify the downloaded file
          cat ./downloaded_logs/getscreen_script.log # Optional: View the content
